# Generated by Django 5.2.7 on 2025-11-21 16:31

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description',
            field=django_summernote.fields.SummernoteTextField(default=''),
        ),
        migrations.AlterField(
            model_name='action',
            name='update',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='description',
            field=django_summernote.fields.SummernoteTextField(default=''),
        ),
    ]
