# Generated by Django 5.2.7 on 2025-12-05 14:48

import django.db.models.deletion
import django.utils.timezone
import django_summernote.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0002_alter_action_description_alter_action_update_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='small_description',
            field=models.CharField(blank=True, default='', help_text='Short summary (max 255 characters).', max_length=255),
        ),
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='action',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='action',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=django_summernote.fields.SummernoteTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='action',
            name='is_progress',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='action',
            name='update',
            field=django_summernote.fields.SummernoteTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='objective',
            name='description',
            field=django_summernote.fields.SummernoteTextField(blank=True, default=''),
        ),
    ]
