# Generated by Django 5.2.7 on 2025-12-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0003_action_created_at_action_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='is_progress',
        ),
    ]
