# Generated by Django 5.2.7 on 2025-12-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0004_remove_action_is_progress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['id']},
        ),
    ]
