# Generated by Django 5.2.7 on 2025-12-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0005_alter_objective_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Inactive'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20),
        ),
    ]
