# Generated by Django 5.2.7 on 2026-01-22 12:08

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0006_alter_objective_options_alter_action_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='description_ga',
            field=django_summernote.fields.SummernoteTextField(blank=True, default='', null=True, verbose_name='Description (Irish)'),
        ),
        migrations.AddField(
            model_name='action',
            name='is_ga_approved',
            field=models.BooleanField(default=False, verbose_name='Irish Content Approved'),
        ),
        migrations.AddField(
            model_name='action',
            name='small_description_ga',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Small Description (Irish)'),
        ),
        migrations.AddField(
            model_name='action',
            name='update_ga',
            field=django_summernote.fields.SummernoteTextField(blank=True, default='', null=True, verbose_name='Update (Irish)'),
        ),
        migrations.AddField(
            model_name='objective',
            name='description_ga',
            field=django_summernote.fields.SummernoteTextField(blank=True, default='', null=True, verbose_name='Description (Irish)'),
        ),
        migrations.AddField(
            model_name='theme',
            name='title_ga',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Title (Irish)'),
        ),
    ]
